// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCyofX2gfe3hK5sGkikwvFmXAdd1yq9fSs',
    appId: '1:909421828884:android:2e7baccc9884937ee58001',
    messagingSenderId: '909421828884',
    projectId: 'cisterpor-fleetsync',
    storageBucket: 'cisterpor-fleetsync.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCgGuBR1024Z5L13fl8kiJ9duNiD04qVEg',
    appId: '1:909421828884:ios:7258bcf05edc705fe58001',
    messagingSenderId: '909421828884',
    projectId: 'cisterpor-fleetsync',
    storageBucket: 'cisterpor-fleetsync.firebasestorage.app',
    iosBundleId: 'com.example.chatLogistica',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB1o0wTDYUag0F5LgeVDRNhdr0d9t1H4zg',
    appId: '1:909421828884:web:83ab0fab65c87942e58001',
    messagingSenderId: '909421828884',
    projectId: 'cisterpor-fleetsync',
    authDomain: 'cisterpor-fleetsync.firebaseapp.com',
    storageBucket: 'cisterpor-fleetsync.firebasestorage.app',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB1o0wTDYUag0F5LgeVDRNhdr0d9t1H4zg',
    appId: '1:909421828884:web:83ab0fab65c87942e58001',
    messagingSenderId: '909421828884',
    projectId: 'cisterpor-fleetsync',
    authDomain: 'cisterpor-fleetsync.firebaseapp.com',
    storageBucket: 'cisterpor-fleetsync.firebasestorage.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCgGuBR1024Z5L13fl8kiJ9duNiD04qVEg',
    appId: '1:909421828884:ios:7258bcf05edc705fe58001',
    messagingSenderId: '909421828884',
    projectId: 'cisterpor-fleetsync',
    storageBucket: 'cisterpor-fleetsync.firebasestorage.app',
    iosBundleId: 'com.example.chatLogistica',
  );

}